name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: <https://harisdev.crm.dynamics.com/>
      PRODUCTION_ENVIRONMENT_URL: <https://harisdev.crm.dynamics.com/>
      CLIENT_ID: <a55651f9-bab6-480d-bd4a-7f0f43aafce3>
      TENANT_ID: <d2a857ff-6cf1-4889-978d-db5ef44bf6fb>      
    secrets:
      envSecret: ${{ secrets.HARIS_DATAVERSE }}
